name: wordpress-nginx
type: service
from: php-nginx
title: Nginx (WordPress)

update: auto
    
labels:
- wordpress

build:
  dockerfile: Dockerfile

configs:
- name: preset
  title: WordPress preset
  filepath: /etc/gotpl/preset/wordpress.conf.tmpl
  config: preset.conf.tmpl

settings:
- name: docroot
  title: Nginx docroot
  from: backend
  var: DOCROOT_SUBDIR

volumes:
- name: wp-content
  from: backend
  title: WP content
  path: /mnt/files

env:
- name: NGINX_VHOST_PRESET
  value: wordpress
